# Generated by Django 4.2.7 on 2025-11-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='URL del avatar del usuario (puede ser una imagen subida o un avatar generado)', max_length=500, null=True),
        ),
    ]
