# Generated by Django 4.2.7 on 2025-11-14 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_type', models.CharField(choices=[('psychology', 'Psicología'), ('nutrition', 'Nutrición'), ('exercise', 'Ejercicio')], max_length=20)),
                ('session_id', models.CharField(blank=True, help_text='ID de sesión para agrupar mensajes', max_length=100, null=True)),
                ('text', models.TextField()),
                ('is_bot', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales (plan_id, routine_id, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['user', 'chat_type', 'session_id'], name='api_chatmes_user_id_da95c3_idx'), models.Index(fields=['user', 'chat_type', '-timestamp'], name='api_chatmes_user_id_c2a55c_idx')],
            },
        ),
    ]
