# Generated by Django 4.2.7 on 2025-11-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.TextField(blank=True, help_text='URL o data URI del avatar del usuario (puede ser una imagen subida en base64, URL de avatar generado, etc.)', null=True),
        ),
    ]
