# Generated by Django 4.2.7 on 2025-11-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userfollow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('post_like', 'Like en Publicación'), ('post_comment', 'Comentario en Publicación'), ('comment_like', 'Like en Comentario'), ('achievement', 'Logro Desbloqueado'), ('user_follow', 'Nuevo Seguidor')], max_length=20),
        ),
    ]
