# Generated by Django 4.2.7 on 2026-01-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_userprofile_current_streak_userprofile_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Biografía o descripción del usuario', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goals',
            field=models.JSONField(blank=True, default=list, help_text="Lista de metas (ej: ['Perder peso', 'Correr 5k'])"),
        ),
    ]
